---
  - name: Create temporary directory to save the script
    tempfile:
      prefix: odoo-users-scripts
      state: directory
    register: temp_dir

  - name: Copy Configure Odoo users Script
    template:
      src: configure_users.py.j2
      dest: "{{ temp_dir.path }}/{{ configure_users_script_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733

  - name: check if script file exist
    stat:
      path: "{{ temp_dir.path }}/{{ configure_users_script_dest }}"
    register: stat_result

  - name: Configure Odoo users using generated script
    command: "python {{ temp_dir.path }}/{{ configure_users_script_dest }}"
    when: stat_result.stat.exists == True

# Bug to Fix : For some reasons, certain rights does not apply on the firts execution, so i re-apply those Rights
  - name: Configure Odoo users using generated script - Second Time
    command: "python {{ temp_dir.path }}/{{ configure_users_script_dest }}"
    when: stat_result.stat.exists == True

  - name: delete temporary files
    file:
      state: absent
      path: "{{ temp_dir.path }}"
