---
  - name: Create temporary directory to save the script
    tempfile:
      prefix: odoo-users-scripts
      state: directory
    register: temp_dir

  - name: Copy Delete Odoo users Script
    template:
      src: delete_users.py.j2
      dest: "{{ temp_dir.path }}/{{ delete_users_script_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733

  - name: check if script file exist
    stat:
      path: "{{ temp_dir.path }}/{{ delete_users_script_dest }}"
    register: stat_result

  - name: Delete Odoo users using generated script
    command: "python {{ temp_dir.path }}/{{ delete_users_script_dest }}"
    when: stat_result.stat.exists == True

  - name: delete temporary files
    file:
      state: absent
      path: "{{ temp_dir.path }}"
